### ISSUE TITLE
Offer to replace dlindahl as a maintainer

### ISSUE THREAD

**Issue by danschmidt5189** [dlindahl/omniauth-cas#52]
Per [this comment](https://github.com/dlindahl/omniauth-cas/issues/7#issuecomment-166497287), I'd like to volunteer to take over as a maintainer from @dlindahl.

I work for the UC Berkeley Libraries, which [use CAS](https://calnetweb.berkeley.edu/calnet-technologists/cas) for both authentication and authorization of a few sites, including geodata.lib.berkeley.edu and altmedia.lib.berkeley.edu. Rails w/Devise has become our default framework for web applications, so we leverage omniauth-cas extensively. And, obviously, we have CAS servers onsite to use for real-world testing.

I don't expect to leave Berkeley anytime soon, but if that did happen we have other developers who could take over from me. As open-source maintainers go, I think we're a relatively safe bet. As a final point in our favor, we also use GitLab and would like to integrate omniauth-cas with that as well.

As for where this is coming from, it seems like this repo is slow to take on changes. The last commit is from 2016, although there are several open issues and pull requests (including [one of mine](https://github.com/dlindahl/omniauth-cas/pull/51), which addresses a [significant bug](#51)). The code is functional, but the tests could use some updates and I suspect a few other open issues are legitimate (#41, #32).

**Comment by dlindahl** [comment]
@danschmidt5189 I've added you as a GitHub collaborator. Can you send me the email address that your Rubygems account is attached to?

**Comment by danschmidt5189** [comment]
Should be on my RubyGems page — https://rubygems.org/profiles/danschmidt5189.

**Comment by danschmidt5189** [comment]
Done, thanks all!

**Comment by samrocketman** [comment]
@dlindahl I recommend transferring this project to a shared organization between you and @danschmidt5189 .  I am mostly recommending this as a protection for @dlindahl because: so long as the project falls under your username your reputation as a software developer depends on the quality of management for this project which you no longer maintain.

By transferring to a shared organization you are still attributed as being the original author but your current and future reputation does not hinge on the quality of maintenance for this project.

Just a friendly recommendation because there have been news articles of projects abused and the person hosting it loses face even though they handed off the project to someone else.

**Comment by danschmidt5189** [comment]
I think that's a good idea, and GitHub org's are free to open source projects so there's no cost.

@dlindahl how do you feel about transferring to `omniauth-cas/omniauth-cas`? We'll need to add any other maintainers there as well.

**Comment by dlindahl** [comment]
Sounds good to me!

**Comment by vjt** [comment]
Great. Please transfer my maintainership, albeit not working on this directly, still using it in many projects thus always always available to fix the occasional bug and run tests.

Cheers and thanks,

**Comment by tagliala** [comment]
Hello,

any chance to move to `omniauth-cas/omniauth-cas` and add also me to maintainers? 

I can see there is already an organization, but I do not know if this is owned by someone interested in maintaining this gem: https://github.com/omniauth-cas
